version: "3"
services:
  db:
    image: mysql:5.7
    container_name: database
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      HOSTNAME: db
    ports:
        - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
        - ./sql:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: server_note
    volumes:
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html/multinote/src
      - ./migrations:/var/www/html/multinote/migrations
      - ./templates:/var/www/html/multinote/templates
#      - ./notes:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  dbdata: